server:
  port: 8084
spring:
  application:
    name: springboot-template
  datasource: # here
    url: jdbc:mysql://8.217.238.90:3306/job_portal?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: LHG
    password: 20040317@Li
  data:
    redis:
      host: 8.217.238.90
      port: 6379
      password: 20040317@Li
      database: 10
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'VOYAGER'
      paths-to-match: '/**'
      # 生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.voyager.controller


#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: false
    username: admin
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 服务模块
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.voyager.domain.pojo
jwt:
  secret: 2we3e4we5w34 #密钥
  expiration: 43200000 #过期时间 12h
